name: New gPRC Release

on:
  pull_request:
    types:
      - closed
    branches:    
      - 'master'

jobs:
  new_release:
    if: github.event.pull_request.merged == true && github.head_ref == 'renovate/grpc-major-upgrade'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install pcregrep
        run: sudo sudo apt-get update -y && sudo apt-get install -y pcregrep
      - name: Get version name
        run: |
          VER=$(pcregrep -o1 "^GRPC_VERSION=\\$\{GRPC_VERSION:-(.*?)\\}$" variables.sh)
          echo "VERSION=v${VER}_0" >> $GITHUB_ENV
      - name: Create new release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release create ${{ env.VERSION }} --generate-notes --repo $GITHUB_REPOSITORY
          
