name: New gPRC Release

on:
  pull_request:
    types:
      - closed
    branches:    
      - 'master'

jobs:
  if_merged:
#     if: github.event.pull_request.merged == true && github.head_ref == 'renovate/grpc-major-upgrade'
    runs-on: ubuntu-latest
    steps:
      - name: Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${pcregrep -o1 "^GRPC_VERSION=\$\{GRPC_VERSION:\-(.*?)\}$" variables.sh}
        run:
          echo ${VERSION}
          
